networks:
  npm-network:
    external: true
services:
  web:
    container_name: louvre_security
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 30001:80
    networks:
      - npm-network